"""Gallery driver: one asset through model → cleanup → audit → render → export.

    blender --background --factory-startup --python build.py -- <asset> <outdir> [res] [samples]

Follows the skill's iron rules for the phases it actually covers. It does NOT
run the skill: the skill drives Blender over MCP and its loop is interactive
(rule 1 get_scene_info per phase, rule 2 get_viewport_screenshot per change,
rule 6 prompt before destroying). This is the scripted-modeling path only.
"""
import bpy, json, os, sys, time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import studio as S
import assets as A

argv = sys.argv[sys.argv.index('--') + 1:]
name, base = argv[0], argv[1]
res = int(argv[2]) if len(argv) > 2 else 1100
samples = int(argv[3]) if len(argv) > 3 else 96

# Output layout from references/naming-conventions.md: one kebab-case folder per
# asset, files prefixed with the same slug.
outdir = os.path.join(base, name)
os.makedirs(outdir, exist_ok=True)
path = lambda suffix: os.path.join(outdir, f"{name}{suffix}")

S.reset()
scene = bpy.context.scene
theme, spec = A.theme_of(name)

t0 = time.time()
obj = A.BUILDERS[name]()
faces_before = S.cleanup(obj)          # rule 10: merge, recalc, apply transforms
tris = S.tri_count(obj)
model_s = time.time() - t0

# Rule 14: 1 Blender unit = 1 metre. Verify rather than assume.
dims = [round(d, 3) for d in obj.dimensions]
scale_ok = all(0.02 < d < 20.0 for d in dims)

# Rule 4: report against the soft budget, never block.
budget_status, budget_msg = S.poly_budget(tris, tier="balanced", kind="prop")

# Rule 19: audit materials BEFORE any GLTF export.
audit = S.material_audit(obj)

raw = path("_original.glb")
size_raw = S.export_glb(obj, raw)      # rule 18: export_apply stays False

size = max(obj.dimensions)
S.backdrop(scene, world_col=spec["world"], ground_col=spec["ground"])
S.three_point(scene, size, accent=spec["accent"], accent_gain=spec["accent_gain"])
S.frame(scene, obj)
render_s = S.render(scene, path(".png"), res=res, samples=samples)

# Rules 7 and 16: the .blend is the recovery point, and it lives with the asset.
bpy.ops.wm.save_as_mainfile(filepath=path(".blend"))

metrics = {
    "asset": name, "theme": theme, "object": obj.name, "tris": tris,
    "faces_before_merge": faces_before, "glb_raw_bytes": size_raw,
    "materials": [m.name for m in obj.data.materials],
    "dim_m": dims, "scale_ok": scale_ok,
    "budget": budget_status, "budget_note": budget_msg,
    "material_audit": audit,
    "model_s": round(model_s, 2), "render_s": round(render_s, 1),
}

# Rule 17: the log records licences. Everything here is generated in-repo, so
# there is no third-party asset to attribute — that is itself worth stating.
with open(path("_log.md"), "w") as f:
    f.write(f"""# {name} — production log

| | |
|---|---|
| Object | `{obj.name}` (data-block `{obj.data.name}`) |
| Theme | {theme} |
| Triangles | {tris:,} |
| Faces before merge | {faces_before:,} |
| Dimensions (m) | {dims[0]} x {dims[1]} x {dims[2]} |
| Scale check (rule 14) | {"1 unit = 1 m, plausible" if scale_ok else "OUT OF RANGE"} |
| Poly budget (rule 4) | {budget_status} — {budget_msg} |
| GLB raw | {size_raw / 1024:.1f} kB |

## Materials

{chr(10).join(f"- `{m.name}`" for m in obj.data.materials)}

## Material export audit (rule 19)

{"No procedural nodes found; nothing is lost on GLTF export."
 if not audit else
 chr(10).join(f"- `{k}`: {', '.join(v)} — WILL BE LOST, bake or simplify" for k, v in audit.items())}

## Licences (rule 17)

All geometry and materials are generated by `assets.py` in this repository, under
its MIT licence. No marketplace download, no AI generation service, no
third-party texture — so there is nothing further to attribute.

## Method

Produced by `build.py` via `blender --background --python`, i.e. the scripted
modeling path. The skill's MCP-driven interactive loop was not used.
""")

print("METRICS " + json.dumps(metrics))
